### ISSUE TITLE
Is there any provision for adding comment in this gem

### ISSUE THREAD

**Issue by prabhakaran-k** [wazery/ratyrate#120]
Dear Author,
         Thanks for the gem. Can you please let me know whether is there any provision for adding comment with rating in this gem.

**Comment by wazery** [comment]
Hi @prabhakaran-k 

Till now the gem doesn't have that functionality, I think it's out of the gem's scope a bit, but will think of adding that.

**Comment by prabhakaran-k** [comment]
Dear Author,
         Thanks for the feedback
