### ISSUE TITLE
Problems adding 'ratyrate' to my project

### ISSUE THREAD

**Issue by maxvlc** [wazery/ratyrate#38]
Hi, I'm newbie on RoR and I'm having a problem adding the Gem into my Gemfile.
## As you said at the Readme, I have added the line "gem 'ratyrate'", but when I execute 'bundle install' I have this error message:

bin/bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
## Could not find gem 'ratyrate (>= 0) ruby' in the gems available on this machine.

And I don't know how to fix this problem... Can you tell me what I'm doing bad?

Rails -v -> 4.1.0
Ruby -v -> ruby 2.1.0p0 (2013-12-25 revision 44422)

Thanks for all...

**Comment by DoniaMourad** [comment]
I followed the tutorial but I get an error 
rate is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.

**Comment by suhabaobaid** [comment]
disable_after_rate: false doesn't show the rating stars to rate again...how can I fix it? Also I can't see the current_user rating after they have rated
