### ISSUE TITLE
undefined method 'average'

### ISSUE THREAD

**Issue by salveta** [wazery/ratyrate#39]
One question
How do I display stars on the index page? 
It get an undefined method `average' for nil:NilClass when i try to put :  Quality  : <%= rating_for @post, "quality", :enable_half => true %>

It's OK on the show page.

**Comment by bachtiarew** [comment]
how do i display stars on other view controller, for example i put in article/index.html.erb or in other view ?
please, give me solution..

**Comment by Nam-9** [comment]
Can someone help me It don't work


 Price  : <%= rating_for @restaurant, 'price' %>
