### ISSUE TITLE
Is there a way to change star Icons?

### ISSUE THREAD

**Issue by junaidehsan12** [wazery/ratyrate#76]
I have used this gem and it is really awesome. I want to customize it a bit and want to show apple icons instead of stars, there is a way mentioned in the tutorials to do it but I think it is not complete or I am not able to understand it. Any help will be really appreciated.

**Comment by junaidehsan12** [comment]
Ah I have solved the issue. This is how we can do it 

= rating_for @request, "rating" , :disable_after_rate => false , star_off: "apple-icon.png"  , :star_on => "apple-icon-fill.png"

Thanks

**Comment by wazery** [comment]
Thanks @junaidehsan12  for mentioning how did you solve it.
