### ISSUE TITLE
Counting single user votes

### ISSUE THREAD

**Issue by ferrettim** [wazery/ratyrate#77]
Maybe I missed it in the documentation, but is there a way to count the number "things" a user has voted for?

**Comment by wazery** [comment]
Can you try `user.ratings_given.count`? 

Please consider starring this gem :star: :smiley:

**Comment by ferrettim** [comment]
Perfect!

**Comment by wazery** [comment]
@ferrettim You are welcome, please consider starring this gem :star: :smiley:
