### ISSUE TITLE
Stars not loading properly in production, works in development

### ISSUE THREAD

**Issue by chbrown1293** [wazery/ratyrate#85]
I am deploying an app on heroku and having difficulty getting stars to load when navigating to the page with a link. I was facing this same issue in development but fixed it by adding:

<%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>

to the body tag of my html. Any ideas as to why this doesnt work in production? (I see that this issue has been brought up before, but am having trouble finding anything useful!!)

**Comment by rmagnum2002** [comment]
@chbrown1293 take a look here http://stackoverflow.com/questions/30291314/ratyrate-stars-not-loading-in-production-heroku and choose the one that works for you.
